In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from regime_ml.data.common.loaders import load_dataframe
from regime_ml.utils.config import load_configs
from regime_ml.regimes.hmm import HMMRegimeDetector

In [3]:
macro_cfg = load_configs()["macro_data"]["regime_universe"]
macro_processed_path = macro_cfg["processed_path"]
pca_feat_path = macro_cfg["ready_features_path"]
raw_feat_path = macro_cfg["raw_features_path"]
raw_path = macro_cfg["raw_path"]

In [15]:
df_pca= load_dataframe(pca_feat_path)
df_pca

,liquidity_pc1,rates_pc1,employment_pc1,rates_pc2,inflation_pc1,growth_pc1
date,,,,,,
2005-06-01,2.049860,-3.328251,-1.939339,-1.163259,-2.493492,0.295478
2005-06-02,1.736682,-3.395609,-1.939339,-1.233491,-2.978902,0.295478
2005-06-03,1.392806,-3.193653,-2.238894,-0.642549,-2.281140,0.295478
2005-06-06,1.484930,-3.267627,-2.127601,-0.712521,-2.573184,0.295478
2005-06-07,1.515064,-3.395043,-2.127601,-1.057686,-3.206393,0.295478
...,...,...,...,...,...,...
2026-01-16,-2.131540,4.052907,0.718882,0.474918,0.577649,-1.667203
2026-01-20,-1.413854,4.463681,0.718882,1.117285,0.542458,-1.667203
2026-01-21,-2.000239,4.063401,0.718882,0.679792,0.725269,-1.667203
2026-01-22,-2.356509,3.972893,0.718882,0.709671,-0.145797,-1.667203
2026-01-23,-2.356509,3.894925,0.718882,0.691029,-0.239268,-1.208418

In [25]:
import plotly.graph_objects as go

fig = go.Figure(data=go.Scatter(x=df_pca.index, y=df_pca["liquidity_pc1"]))
fig.show()

In [8]:
from regime_ml.regimes.hmm import initialise_emissions
from regime_ml.regimes.hmm import initialise_transitions
from regime_ml.regimes.hmm import initialise_probabilities

fitted_models = {}
count = 0
for split_date in ["2019-01-01"]: #['2018-01-01','2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01']:
    df_train = df_feat.loc[:split_date]
    X_train = df_train.values

    for n_regimes in [3, 4]:
        init_startprob = initialise_probabilities(n_regimes=n_regimes)

        for covariance_type in ['diag']:
            init_means, init_covars, scaler = initialise_emissions(df_train, n_clusters=n_regimes, covariance_type=covariance_type)

            for p_stay in [0.9, 0.95, 0.99]:
                init_transmat = initialise_transitions(n_regimes=n_regimes, p_stay=p_stay)

                model = HMMRegimeDetector(
                    n_regimes=n_regimes,
                    covariance_type=covariance_type,
                    startprob=init_startprob,
                    transmat=init_transmat,
                    means=init_means,
                    covars=init_covars,
                    feature_names=feature_names,
                )

                X_train_scaled = scaler.fit_transform(X_train)
                fitted_model = model.fit(X_train_scaled)
                fitted_models[f"{count}"] = {
                    "model": fitted_model,
                    "split_date": split_date,
                    "n_regimes": n_regimes,
                    "covariance_type": covariance_type,
                    "p_stay": p_stay,
                    "scaler": scaler,
                }
                count += 1

NameError: name 'df_feat' is not defined

In [15]:
fitted_models

{'0': {'model': HMMRegimeDetector(is_fitted=True),
  'split_date': '2019-01-01',
  'n_regimes': 3,
  'covariance_type': 'diag',
  'p_stay': 0.9,
  'scaler': StandardScaler()},
 '1': {'model': HMMRegimeDetector(is_fitted=True),
  'split_date': '2019-01-01',
  'n_regimes': 3,
  'covariance_type': 'diag',
  'p_stay': 0.95,
  'scaler': StandardScaler()},
 '2': {'model': HMMRegimeDetector(is_fitted=True),
  'split_date': '2019-01-01',
  'n_regimes': 3,
  'covariance_type': 'diag',
  'p_stay': 0.99,
  'scaler': StandardScaler()},
 '3': {'model': HMMRegimeDetector(is_fitted=True),
  'split_date': '2019-01-01',
  'n_regimes': 4,
  'covariance_type': 'diag',
  'p_stay': 0.9,
  'scaler': StandardScaler()},
 '4': {'model': HMMRegimeDetector(is_fitted=True),
  'split_date': '2019-01-01',
  'n_regimes': 4,
  'covariance_type': 'diag',
  'p_stay': 0.95,
  'scaler': StandardScaler()},
 '5': {'model': HMMRegimeDetector(is_fitted=True),
  'split_date': '2019-01-01',
  'n_regimes': 4,
  'covariance_type': 'diag',
  'p_stay': 0.99,
  'scaler': StandardScaler()}}

In [16]:
from regime_ml.regimes.evaluation import compare_hmm_models
results = compare_hmm_models(df_feat, fitted_models)

KeyError: 'n_features'

In [9]:
pd.DataFrame(results)

                                                                          0
n_obs_full                                                             5361
n_obs_is                                                               3594
n_obs_oos                                                              1767
regime_stability          {'avg_persistence': 71.48, 'std_persistence': ...
entropy_balance           {'entropy_balance': 0.05176965266565841, 'entr...
transition_matrix_sanity  {'median_implied_duration': 103.05977138299204...
macro_coherence           {'maha_min': 1.4839864120121968, 'maha_median'...
in_sample                 {'regime_stability': {'avg_persistence': 79.86...
out_of_sample             {'regime_stability': {'avg_persistence': 55.21...

In [10]:
records = [
    {"model_id": mid, **pd.json_normalize(v, sep=".").iloc[0].to_dict()}
    for mid, v in results.items()
]
df = pd.DataFrame(records).set_index("model_id")

In [11]:
# NOTE: investigate why nearly have of the tv_distances are not valid (does this make sense or is there a fundamental issue with the models)
from regime_ml.data.macro import build_featuregroup_map
_map = build_featuregroup_map(df_feat.columns)
_map

{'CFNAI_level_zscore_36': 'growth',
 'CFNAI_diff_1_zscore_36': 'growth',
 'DGS10_level_zscore_252': 'rates',
 'DGS10_diff_21_zscore_252': 'rates',
 'DGS10_diff_1_rollingstd_21_zscore_126': 'rates',
 'DGS2_level_zscore_252': 'rates',
 'ICSA_movingaverage_4_zscore_50': 'employment',
 'ICSA_movingaverage_4_pctchange_13_zscore_50': 'employment',
 'ICSA_movingaverage_4_pctchange_4_zscore_25': 'employment',
 'INDPRO_yoy_12_zscore_36': 'growth',
 'INDPRO_yoy_12_diff_1_zscore_36': 'growth',
 'INDPRO_pctchange_3_zscore_36': 'growth',
 'NFCI_level_zscore_50': 'liquidity',
 'NFCI_diff_21_zscore_50': 'liquidity',
 'NFCI_diff_5_diff_5_zscore_25': 'liquidity',
 'PCEPILFE_yoy_12_zscore_36': 'inflation',
 'PCEPILFE_yoy_12_diff_1_zscore_36': 'inflation',
 'PCEPILFE_pctchange_1_zscore_36': 'inflation',
 'T10Y3M_level_zscore_252': 'rates',
 'T10Y3M_diff_21_zscore_252': 'rates',
 'T10Y3M_diff_5_zscore_126': 'rates',
 'VIXCLS_level_zscore_63': 'stress',
 'VIXCLS_diff_5_zscore_126': 'stress',
 'VIXCLS_movingaverage_21_diff_21_zscore_252': 'stress',
 'VIXCLS_pctchange_1_rollingstd_21_zscore_126': 'stress'}

In [13]:
from regime_ml.regimes.selection import select_best_hmm_model
best_id, leaderboard, rejected = select_best_hmm_model(results)
display(leaderboard[["model_id","final_score","macro_score","transition_score","stability_score","oos_macro_score"]])

,model_id,final_score,macro_score,transition_score,stability_score,oos_macro_score
0,0,0.871692,1.0,0.572306,1.0,1.0

In [14]:
best_model = fitted_models["0"]
model = best_model["model"]
selected_features = model.feature_names
split_date = best_model["split_date"]

best_model

{'model': HMMRegimeDetector(is_fitted=True),
 'split_date': '2019-01-01',
 'n_features': 5,
 'n_regimes': 4,
 'covariance_type': 'full',
 'p_stay': 0.9,
 'scaler': StandardScaler()}

In [1]:
from regime_ml.regimes.labeling import label_regimes
import numpy as np

df_selected = df_feat[selected_features]
X_full = df_selected.values
X_scaled = best_model["scaler"].fit_transform(X_full)

filtered_proba = model.filter_proba(X_scaled)
filtered_regimes = np.argmax(filtered_proba, axis=1)
smoothed_proba = model.smooth_proba(X_scaled)
predicted_proba = model.forecast_n_steps(filtered_proba, 50)

labels_info = label_regimes(
    X=X_scaled,
    proba=filtered_proba,
    feature_names=selected_features
)

NameError: name 'df_feat' is not defined

In [16]:
from regime_ml.regimes.visualisation import plot_regime_timeseries
from regime_ml.regimes.visualisation import plot_ticker_by_regime

fig1 = plot_regime_timeseries(df_selected, filtered_regimes, predicted_proba, regime_names=labels_info["state_labels"])
fig2 = plot_ticker_by_regime("SPY", df_selected.index, filtered_regimes, regime_names=labels_info["state_labels"])
fig3 = plot_ticker_by_regime("^VIX", df_selected.index, filtered_regimes, regime_names=labels_info["state_labels"])

fig2.show()
fig3.show()
fig1.show()

Downloading SPY data from 2004-09-01 to 2026-01-23...
Downloading ^VIX data from 2004-09-01 to 2026-01-23...

In [17]:
from regime_ml.regimes.evaluation import equity_metrics_by_regime
import yfinance as yf
filtered_regimes = list(map(lambda x: labels_info["state_labels"][x], filtered_regimes))

df_sap = yf.download("SAP", start=df_feat.index[0], end=df_feat.index[-2], multi_level_index=False)["Close"].reindex(df_feat.index) # type: ignore

df_equity_metrics = equity_metrics_by_regime(df_sap, filtered_regimes)
df_equity_metrics

[*********************100%***********************]  1 of 1 completed

,regime,n_days,mean_daily_ret,ann_return,ann_vol,sharpe,max_drawdown,up_day_frac
0,Risk On - Expansion,587,0.001488,0.454603,0.294760,1.272261,-0.212257,0.553663
1,Risk On - Policy-Contstrained Expansion,2124,0.000606,0.164834,0.241677,0.631521,-0.373861,0.537194
2,Risk On - Stagflation,1979,0.000573,0.155419,0.255171,0.566306,-0.378489,0.513896
3,Risk Off - Recession,642,-0.000528,-0.124693,0.407587,-0.326667,-0.638359,0.498442

In [18]:
model0 = fitted_models["0"]["model"]
#model1 = fitted_models["1"]["model"]

In [25]:
filtered_proba0 = model0.filter_proba(X_scaled)
filtered_regimes0 = np.argmax(filtered_proba0, axis=1)
smoothed_proba0 = model0.smooth_proba(X_scaled)

labels_info0 = label_regimes(
    X=X_scaled,
    proba=smoothed_proba0,
    feature_names=selected_features
)

# filtered_proba1 = model1.filter_proba(X_scaled)
# filtered_regimes1 = np.argmax(filtered_proba1, axis=1)
# smoothed_proba1 = model1.smooth_proba(X_scaled)

# labels_info1 = label_regimes(
#     X=X_scaled,
#     proba=smoothed_proba1,
#     feature_names=selected_features
# )

fig0 = plot_ticker_by_regime("^VIX", df_selected.index, filtered_regimes0, regime_names=labels_info0["state_labels"])
# fig1 = plot_ticker_by_regime("^VIX", df_selected.index, filtered_regimes1, regime_names=labels_info1["state_labels"])

fig0.show()

Downloading ^VIX data from 2004-09-01 to 2026-01-23...

In [23]:
df_sap = yf.download("SAP", start=df_feat.index[0], end=df_feat.index[-2], multi_level_index=False)["Close"].reindex(df_feat.index) # type: ignore

df_equity_metrics0 = equity_metrics_by_regime(df_sap, filtered_regimes0)
# df_equity_metrics1 = equity_metrics_by_regime(df_sap, filtered_regimes1)

display(df_equity_metrics0)
# display(df_equity_metrics1)

[*********************100%***********************]  1 of 1 completed

,regime,n_days,mean_daily_ret,ann_return,ann_vol,sharpe,max_drawdown,up_day_frac
0,3,587,0.001488,0.454603,0.294760,1.272261,-0.212257,0.553663
1,0,2124,0.000606,0.164834,0.241677,0.631521,-0.373861,0.537194
2,1,1979,0.000573,0.155419,0.255171,0.566306,-0.378489,0.513896
3,2,642,-0.000528,-0.124693,0.407587,-0.326667,-0.638359,0.498442